# Conclusion

The main takeaway of this analysis was that there is a positive correlation overall between the percent of time spent in drought, and the relative number of wildfires a state or region experiences. The strength of this correlation varies by region - states that are not typically dry may experience a relatively extreme number of wildfires in a severe drought, while a more drought-prone state may have a more constant, though potentially high, number of fires.

The limitations of this exploration was the completeness of the NFIRS databaset. As mentioned on the [NFIRS site](https://www.fema.gov/about/openfema/data-sets/fema-usfa-nfirs-annual-data), the dataset is only a subset of the true number of fires that occur in the United States and should not be used to determine the total number of fires or total loss from fires for any given time. Because this data is only a subset, and is recorded by Fire Department personnel, there is a chance the dataset is not wholly reflective of the wildfires situation in the United States. There could be biases if certain states or regions are more active in recording NFIRS incidents. The data also had to be filtered to include certain wildfire-specific incident types. Because the incident type is determine by a human, there is potential for mis-classification as well as missing values. To deal with these challenges we did not use the raw number of wildfires in a state when comparing with drought - rather, we used the relative number of wildfires (z-score) in particular states, and examined trends in wildfires over time. 

For future analysis, it would be interesting to analyze data more in-depth at the county level. The USDM dataset contains extensive and high-quality county-wide data, but NFIRS was more useful at the state level (the county was not recorded in NFIRS incidents and had to be merged from zipcode). A more extensive wildfire dataset, or more extensive analysis on NFIRS, could reveal how drought affects wildfires in the most susceptible states, such as California.
